[package]
name = "oas-rs-macros"
version = "0.7.0"
edition = "2024"
description = "Derive macros for oas-rs"
license = "MIT"
rust-version = "1.88"
repository = "https://github.com/sevlumen/rust-openapi"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["derive"] }
